badger_project/badge_tracker/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from .views import SearchListView, BadgeDetailView, BadgeListView

urlpatterns = [
    url(r'^$', SearchListView.as_view(), name="search"),
    url(r'^list/$', BadgeListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w\d\-\_]+)/$', BadgeDetailView.as_view(), name='detail'),
]

badger_project/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from badge_tracker.views import IndexListView

urlpatterns = [
    url(r'^$', IndexListView.as_view(), name="home"),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include("badger_project.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^badge/', include("badger_project.badge_tracker.urls", namespace="badge")),

    # Your stuff: custom urls includes go here


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception("Bad Request!")}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception("Permissin Denied")}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception("Page not Found")}),
        url(r'^500/$', default_views.server_error),
    ]

badger_project/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

badger_project/badge_tracker/models.py
from __future__ import unicode_literals

from django.core.urlresolvers import reverse
from django.db import models
from django.contrib import admin
from django.utils.translation import ugettext_lazy as _

from django_extensions.db.models import TimeStampedModel, ActivatorModel, TitleSlugDescriptionModel, TitleDescriptionModel

from .managers import BadgeManager, MyBadgeManager


def get_image_name(instance, filename):
    return 'badges/image.png'

class Category(TitleSlugDescriptionModel, models.Model):
    order = models.IntegerField(default=10)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['order','title']

class Platform(TitleSlugDescriptionModel, models.Model):
    order = models.IntegerField(default=10)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['order','title']


class Subject(TitleSlugDescriptionModel, models.Model):
    order = models.IntegerField(default=10)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['order','title']


class Criteria(TitleDescriptionModel, models.Model):
    def __str__(self):
        return self.title


class Display(TimeStampedModel, models.Model):
    type = models.CharField(max_length=10, choices=(('image','image'),('video','video')), default='image')
    uploadedResource = models.ImageField(upload_to="display_uploads", blank=True, null=True, verbose_name="Uploaded Resource")
    linkedResource = models.URLField(blank=True, verbose_name="Linked Resource")

    def __str__(self):
        return self.type


class Badge(TimeStampedModel, TitleSlugDescriptionModel, ActivatorModel, models.Model):
    """
    title = models.CharField(_('title'), max_length=255)
    description = models.TextField(_('description'), blank=True, null=True)
    slug = AutoSlugField(_('slug'), populate_from='title')
    created = CreationDateTimeField(_('created'))
    modified = ModificationDateTimeField(_('modified'))
    status = models.IntegerField(_('status'), choices=STATUS_CHOICES, default=ACTIVE_STATUS)
    activate_date = models.DateTimeField(blank=True, null=True, help_text=_('keep empty for an immediate activation'))
    deactivate_date = models.DateTimeField(blank=True, null=True, help_text=_('keep empty for indefinite activation'))
    """
    image = models.URLField(verbose_name="Image Link")
    destinationLink = models.URLField(blank=True)
    displays = models.ManyToManyField(Display, blank=True)
    categories = models.ManyToManyField(Category)
    platforms = models.ManyToManyField(Platform)
    subjects = models.ManyToManyField(Subject)
    criteria = models.ForeignKey(Criteria, blank=True, null=True)
    popularity = models.IntegerField(default=0)

    objects = BadgeManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('badge:detail', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['-popularity', 'title', 'modified']


class MyBadge(TimeStampedModel, models.Model):
    badge = models.ForeignKey(Badge, on_delete=models.CASCADE)
    awarded = models.BooleanField(default=False)

    objects = MyBadgeManager()

    def __str__(self):
        return self.badge.title



admin.site.register(Category)
admin.site.register(Platform)
admin.site.register(Subject)
admin.site.register(Badge)
admin.site.register(MyBadge)
admin.site.register(Criteria)

badger_project/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.contrib import admin
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from django_extensions.db.models import TitleDescriptionModel

from badger_project.badge_tracker.models import Subject, MyBadge


SUBJECT_CHOICES = (
    ("All Subjects","All Subjects"),
    ("No Subjects","No Subjects"),
    ("English-Reading","English-Reading"),
    ("Math","Math"),
    ("Science","Science"),
    ("Social Studies","Social Studies"),
    ("Special Education","Special Education"),
    ("Language Studies","Language Studies"),
    ("CATE","Career and Technology Education")
)

SCHOOL_CHOICES = (
    ("none", 'None'),
    ('LES', 'Lillian Elementary'),
    ('AES', 'Elementary South'),
    ('AEN', 'Elementary North'),
    ('AIS', 'Intermediate'),
    ('AJH', 'Junior High'),
    ('AHS', 'High School'),
    ('Administration', 'Administration'),
    ('Operations', 'Operations'),
    ('Special Services', 'Special Services'),
    ('Technology', 'Technology'),
)

GRADE_CHOICES = (
    ("none","None"),
    ("K","Kindergarten"),
    ("1","1st"),
    ("2","2nd"),
    ("3","3rd"),
    ("4","4th"),
    ("5","5th"),
    ("6","6th"),
    ("7","7th"),
    ("8","8th"),
    ("9","9th"),
    ("10","10th"),
    ("11","11th"),
    ("12","12th"),
)

class Campus(TitleDescriptionModel, models.Model):
    def __str__(self):
        return self.title


class Grade(TitleDescriptionModel, models.Model):
    def __str__(self):
        return self.title



@python_2_unicode_compatible
class User(AbstractUser):
    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    campus = models.ManyToManyField(Campus, blank=True)
    grade = models.ManyToManyField(Grade, blank=True)
    job = models.CharField(max_length=85, verbose_name='Occupation', default="Teacher")
    subject = models.ManyToManyField(Subject, blank=True)
    roomNumber = models.CharField(max_length=8, blank=True)
    phoneExtension = models.IntegerField(default=0)
    badges = models.ManyToManyField(MyBadge, blank=True)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})



admin.site.register(Campus)
admin.site.register(Grade)

badger_project/badge_tracker/forms.py
from django import forms


class SearchForm(forms.Form):
    search = forms.CharField(
        max_length=140,
        min_length=3,
        strip=True,
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'placeholder':'search...',
                'required':'true'
            }))

badger_project/badge_tracker/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse_lazy
from django.views.generic import DetailView, ListView, RedirectView, UpdateView, CreateView, DeleteView

from braces.views import LoginRequiredMixin

from .models import MyBadge, Badge, Category, Platform, Subject
from .forms import SearchForm


class SearchFormMixin(object):

    def get_context_data(self, **kwargs):
        context = super(SearchFormMixin, self).get_context_data(**kwargs)
        context['searchForm'] = SearchForm
        return context


class IndexListView(LoginRequiredMixin, SearchFormMixin, ListView):
    model = MyBadge
    select_related = ['badge']

    def get_context_data(self, **kwargs):
        context = super(IndexListView, self).get_context_data(**kwargs)
        context['awarded'] = self.model.objects.awarded_badges(self.request.user)
        context['wanted'] = self.model.objects.wanted_badges(self.request.user)
        return context


class SearchListView(LoginRequiredMixin, SearchFormMixin, ListView):
    model = Badge
    template_name = 'badge_tracker/search_list.html'
    context_object_name = 'badges'

    def get_queryset(self):
        query = self.request.GET['search']
        return self.model.objects.search_badges(query)


class BadgeDetailView(LoginRequiredMixin, SearchFormMixin, DetailView):
    model = Badge


class BadgeListView(LoginRequiredMixin, SearchFormMixin, ListView):
    model = Badge

    def get_context_data(self, **kwargs):
        context = super(BadgeListView, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['platforms'] = Platform.objects.all()
        context['subjects'] = Subject.objects.all()
        return context

badger_project/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from braces.views import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

badger_project/templates/base.html
{% load staticfiles i18n %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Indian Badger{% endblock title %}</title>

    {% block css %}
    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">

    <!-- Custom Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}" type="text/css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/creative.css' %}" type="text/css">
    {% endblock css %}


    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.min.js"></script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body id="page-top" data-spy="scroll">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top" data-spy="affix" data-offset-top="100">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="{% url 'home' %}">
                    <span><img class="responsive" src="{% static 'images/indianBadgerLogoColor.png' %}" alt="AISD.me" style="width:50px;margin-top:-10px;"></span>
                    <span>Indian Badger</span>
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="{% url 'home' %}">My Badges</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="{% url 'badge:list' %}">Browse</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    {% block header %}
  <header style="min-height:220px;">
      <div class="header-content">
          <div class="header-content-inner">
              <div id="validateError"></div>
              <form id="search-form" action="{% url 'badge:search' %}" method="get" autocomplete="off">
                <i class="fa fa-search long-fa"></i>
                {{ searchForm.search }}
                {{ searchForm.search.errors }}
                <button type="submit" class="btn btn-primary btn-lg btn-shorten fadeOut">
                  <i class="fa fa-sun-o fa-fw"></i><span>  Find a Badge</span>
                </button>
              </form>
          </div>
      </div>
  </header>
    {% endblock header %}



      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %} text-center">{{ message }}</div>
          {% endfor %}
      {% endif %}


      {% block content %}
      {% endblock content %}


    <aside class="bg-dark">
        <div class="container text-center">
            <div class="call-to-action">
                <h2>See What Else We Have Goin' On In AISD Technology</h2>
                <a href="https://plus.google.com/u/0/communities/116746578932396922056" class="btn btn-default btn-xl wow tada" title="Google+" target="_blank"><i class="fa fa-google-plus fa-3x"></i></a> |
                <a href="https://twitter.com/AISDTechnology" class="btn btn-default btn-xl wow tada" title="Twitter" target="_blank"><i class="fa fa-twitter fa-3x"></i></a> |
                <a href="https://www.facebook.com/Alvarado-Instructional-Technology-Specialists-387274611372255" class="btn btn-default btn-xl wow tada" title="Facebook" target="_blank"><i class="fa fa-facebook fa-3x"></i></a> |
                <a href="https://www.pinterest.com/alvaradoits" class="btn btn-default btn-xl wow tada" title="Pinterest" target="_blank"><i class="fa fa-pinterest fa-3x"></i></a>
            </div>
        </div>
    </aside>

    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Need Help!</h2>
                    <h2 class="section-heading">Let's Get In Touch!</h2>
                    <hr class="primary">
                </div>
                <div class="col-lg-4 col-lg-offset-2 text-center">
                    <i class="fa fa-phone fa-3x wow bounceIn"></i>
                    <p>ext - 1160</p>
                    <p>or</p>
                    <p>ext - 1161</p>
                </div>
                <div class="col-lg-4 text-center">
                    <i class="fa fa-envelope-o fa-3x wow bounceIn" data-wow-delay=".1s"></i>
                    <p><a href="https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=rboyett@alvaradoisd.net" target="_blank">rboyett@alvaradoisd.net</a></p>
                    <p><a href="https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=jhenderson@alvaradoisd.net" target="_blank">jhenderson@alvaradoisd.net</a></p>
                </div>
            </div>
        </div>
    </section>


    {% block modal %}{% endblock modal %}


    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'js/jquery.easing.min.js' %}"></script>
    <script src="{% static 'js/jquery.fittext.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/jquery.form.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'js/creative.js' %}"></script>
    <script src="https://unpkg.com/imagesloaded@4.1/imagesloaded.pkgd.min.js"></script>
    {% block extraScript %}{% endblock extraScript %}
</body>

</html>